export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CARTITEM_QTY = 'UPDATE_CARTITEM_QTY';
export const CART_RESET = 'CART_RESET';
export const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS';

export const CONFIRM_CART_ITEMS_REQUEST = 'CONFIRM_CART_ITEMS_REQUEST'
export const CONFIRM_CART_ITEMS_SUCCESS = 'CONFIRM_CART_ITEMS_SUCCESS'
export const CONFIRM_CART_ITEMS_FAIL = 'CONFIRM_CART_ITEMS_FAIL'
export const CHANGE_CART_ITEMS = 'CHANGE_ORDER_ITEMS'