export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_CATEGORY_PRODUCTS_REQUEST = "GET_CATEGORY_PRODUCTS_REQUEST";
export const GET_CATEGORY_PRODUCTS_SUCCESS = "GET_CATEGORY_PRODUCTS_SUCCESS";
export const GET_CATEGORY_PRODUCTS_FAIL = "GET_CATEGORY_PRODUCTS_FAIL";

export const GET_GENDER_PRODUCTS_REQUEST = "GET_GENDER_PRODUCTS_REQUEST";
export const GET_GENDER_PRODUCTS_SUCCESS = "GET_GENDER_PRODUCTS_SUCCESS";
export const GET_GENDER_PRODUCTS_FAIL = "GET_GENDER_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";

export const GET_TOP_PRODUCTS_REQUEST = "GET_TOP_PRODUCTS_REQUEST";
export const GET_TOP_PRODUCTS_SUCCESS = "GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAIL = "GET_TOP_PRODUCTS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAIL = "ADD_PRODUCT_REVIEW_FAIL";